/**
 * Streaming gui timeline theme (Optimal - no charts, inserting, dialogs and vscode authority no settings, no timeline...)
 * @author leroyron / http://leroy.ron@gmail.com
 */
(function(c,m){this.gui={};this.gui.addon={bind:{}};this.gui.addon.bind.onchange=function(a,b){a.onChange(function(a){b(this)})};var f=function(a,b,c){a[b]||(a[b]=function(){this[b+"Callbacks"]()});a[b+"Calls"]=[];a[c]=0;a[b+"Callbacks"]=function(){for(var a=0;a<this[c];a++)this[b+"Calls"][a][1](this[b+"Calls"][a][0])}};this.gui.addon.bind.oninit=function(a,b,c){b.initCalls||f(b,"init","inclen");b.initCalls.push([a,c]);b.inclen++};this.gui.addon.bind.onready=function(a,b,c){b.readyCalls||f(b,"ready",
"rdclen");b.readyCalls.push([a,c]);b.rdclen++};this.gui.addon.bind.onupdate=function(a,b,c){b.updateCalls||f(b,"update","upclen");b.updateCalls.push([a,c]);b.upclen++};this.gui.addon.bind.onruntime=function(a,b,c){b.runtimeCalls||f(b,"runtime","ruclen");b.runtimeCalls.push([a,c]);b.ruclen++};this.gui.addon.bind.onrevert=function(a,b,c){b.revertCalls||f(b,"revert","rrclen");b.revertCalls.push([a,c]);b.rrclen++};this.gui.addon.bind.onpass=function(a,b,c){b.passCalls||f(b,"pass","paclen");b.passCalls.push([a,
c]);b.paclen++};m(this.gui,this.Streaming,this.app)})(this.dat,function(c,m,f){c.addon.app=function(a){var b={};a.fullScreenHandler="undefined"!=typeof document.fullscreenElement?{event:"fullscreenChange",state:"fullscreen"}:"undefined"!=typeof document.msFullscreenElement?{event:"MSFullscreenChange",state:"fullscreen"}:"undefined"!=typeof document.mozFullScreenElement?{event:"mozfullscreenchange",state:"mozFullScreen"}:"undefined"!=typeof document.webkitFullscreenElement?{event:"webkitfullscreenchange",
state:"webkitIsFullScreen"}:{event:"fullscreenchange",state:"fullscreen"};document.addEventListener(a.fullScreenHandler.event,function(d){d.preventDefault();a.fullscreenEnabled=document[a.fullScreenHandler.state];window.setTimeout(window.onresize(),1E3)},!1);b.resolution={r2160p:[3840,2160],r1440p:[2560,1440],r1080p:[1920,1080],r720p:[1280,720],r480p:[854,480],r360p:[640,360],r240p:[426,240]};f.resolution.update=function(a){window.changeResolution({width:b.resolution[a][0],
height:b.resolution[a][1]})}("r720p");return b}(c);c.addon.Streaming=c.addon.Streaming=m.prototype.addon;var a=c.addon.Streaming.timeframe,b=c.addon.Streaming.timeframe.timeline=function(b,c){var d={segment:0,init:void 0,ready:void 0,update:function(a){d.updateCallbacks()},updateCalls:[],upclen:0,updateCallbacks:function(){for(var a=0;a<this.upclen;a++)this.updateCalls[a][1](this.updateCalls[a][0])},pass:function(a){d.passCallbacks()},passCalls:[],paclen:0,passCallbacks:function(){for(var a=0;a<this.paclen;a++)this.passCalls[a][1](this.passCalls[a][0])}},
e=function(){a.duration>a.length&&(a.duration+=a.length-a.duration);d.seek.position=a.duration/a.length*100;d.seek.position-d.prevSegmentPos>d.segmentPos-d.prevSegmentPos&&d.checkPassSegment();d.update()};d.seek={position:void 0,slider:{},span:{},bar:{},info:{}};d.prevSegmentPos=void 0;d.segmentPos=void 0;d.nextSegmentPos=void 0;d.passSegment=void 0;d.callbackPass={list:[],count:0};var h,g,f,x,u,r,y,k,t,m,v,p,q,n;d.refresh=function(){h=document.getElementById("actionjson");g=document.getElementsByClassName("actionscript");
f=g.length;x=new Int32Array(new ArrayBuffer(4*f));for(var a=0;a<f;a++)x[a]=parseInt(g[a].data);u=document.getElementById("soundjson");r=document.getElementsByClassName("soundscript");y=r.length;k=document.getElementById("commentjson");t=document.getElementsByClassName("commentscript");m=t.length;v=document.getElementById("segmentjson");p=document.getElementsByClassName("segmentscript");q=p.length;n=new Int32Array(new ArrayBuffer(4*q));for(a=0;a<q;a++)n[a]=parseInt(p[a].data)||1;this.checkPassSegment()};
d.checkPassSegment=function(){for(var a=this.passSegment=0;a<q;a++)this.seek.position>=n[a]&&this.passSegment++;this.prevSegmentPos=n[this.segment-1]||0;this.segmentPos=n[this.segment]||100;this.nextSegmentPos=n[this.segment+1]||100;this.pass()};d.removeInsertsNear=function(a,b,d){};d.removeInsertAt=function(a,b){};d.destroy=function(b,d){b=b||["action","sound","comment","segment"];b=b.constructor===Array?b:[b];for(var c=0;c<b.length;c++)if(a.clearRuntimeAuthority(b[c]),"action"==b[c]){for(var e=
f-1;-1<e;e--)g[e]&&document.getElementsByTagName("body")[0].removeChild(g[e]);h&&document.getElementsByTagName("body")[0].removeChild(h)}else if("sound"==b[c]){for(e=y-1;-1<e;e--)r[e]&&document.getElementsByTagName("body")[0].removeChild(r[e]);u&&document.getElementsByTagName("body")[0].removeChild(u)}else if("comment"==b[c]){for(e=m-1;-1<e;e--)t[e]&&document.getElementsByTagName("body")[0].removeChild(t[e]);k&&document.getElementsByTagName("body")[0].removeChild(k)}else if("segment"==b[c]){for(e=
q-1;-1<e;e--)p[e]&&document.getElementsByTagName("body")[0].removeChild(p[e]);v&&document.getElementsByTagName("body")[0].removeChild(v)}("undefined"==typeof d||d)&&this.refresh()};d.destroy();var l=document.getElementsByClassName("rec");window.clearInterval(window.interval);window.interval=window.setInterval(function(){for(var a=0;a<l.length;a++)"rec on"==l[a].className?l[a].className="rec off":"rec off"==l[a].className?l[a].className="rec on":"rec seg"==l[a].className&&(l[a].innerHTML=d.segment)},
1E3);var w=function(){setTimeout(function(){if(a.init&&d.init){4!=d.initCalls.length&&w();d.init();var b=function(){setTimeout(function(){a.ready&&d.ready?(this.app.ready=!0,d.ready()):b()},0)};b()}else w()},0)};w();b.addon.bind.onrevert(d.seek,a,function(b,c){a.duration=c;e();d.checkPassSegment()});b.addon.bind.onruntime(d.seek,a,e);return d}(c,f);(function(c){var e=c.addon.Streaming.timeframe.timeline.seek;a.goTo=function(d){a.duration=d||e.position/100*a.length<<0;a.syncing();b.checkPassSegment()};
c.addon.bind.onready(e,b,function(){setTimeout(function(){a.run()},500)});return e})(c);var k=c.addon.Streaming.timeframe.timeline.seek.insert=function(c,e){var d={select:"nothing",delta:"nothing",position:{},dragging:!1},f=function(b,d,c,e,f){var g=document.createElement("script");g.type="text/javascript";g.async=!1;f?g.id=b+"json":(g.setAttribute("class",b+"script"),g.data=e);g.readyState?g.onreadystatechange=function(){if("loaded"==g.readyState||"complete"==g.readyState)g.onreadystatechange=null,
c(window.Authority,b,e),window.Authority=void 0,h.finish++,h.entry==h.finish&&a._ready()}:g.onload=function(){c(window.Authority,b,e);window.Authority=void 0;h.finish++;h.entry==h.finish&&a._ready()};g.src=d;document.getElementsByTagName("body")[0].appendChild(g)},h={entry:0,finish:0};d.load=function(a,b,d){var c=d||"";e.codesettingLoc=e.codesetting?e.codesetting+"/":"";h.entry++;f(a,c+("user/"+e.codesettingLoc+a+".js"),function(d){for(var g in d)h.entry++,f(a,c+("user/"+e.codesettingLoc+a+g+".js"),b,g,
!1)},0,!0)};d.reload=function(a,b,d){this.load("action",this.action.init,e.vscode._fileLocal);this.load("sound",this.sound.init,e.vscode._fileLocal);this.load("comment",this.comment.init,e.vscode._fileLocal);this.load("segment",this.segment.init,e.vscode._fileLocal)};d.insertAuthorities=function(d){for(var c in d){this.delta=c;for(var e in d[c])this.position=e/a.length*100,a.runtimeAuthority(d[c][e].Authority,this.delta,e)}b.refresh();this.select=this.delta="nothing"};return d}(c,f);c.addon.Streaming.timeframe.timeline.seek.insert.comment=
function(c,e){var d={init:function(d,c,e){a.runtimeAuthority(d,c,e);b.refresh()}};c.addon.bind.oninit(d,b,function(a){k.load("comment",a.init,e.vscode._fileLocal)});return d}(c,f);c.addon.Streaming.timeframe.timeline.seek.insert.segment=function(c,e){var d={init:function(d,c,e){a.runtimeAuthority(d,c,e);b.refresh()}};c.addon.bind.oninit(d,b,function(a){k.load("segment",a.init,e.vscode._fileLocal)});return d}(c,f);c.addon.Streaming.timeframe.timeline.seek.insert.action=function(c,e){var d={init:function(d,
c,e){a.runtimeAuthority(d,c,e);b.refresh()}};c.addon.bind.oninit(d,b,function(a){k.load("action",a.init,e.vscode._fileLocal)});return d}(c,f);c.addon.Streaming.timeframe.timeline.seek.insert.sound=function(c,e){var d={init:function(c,d,e){a.runtimeAuthority(c,d,e);b.refresh()}};c.addon.bind.oninit(d,b,function(a){k.load("sound",a.init,e.vscode._fileLocal)});return d}(c,f)});